### ISSUE TITLE
Windows 10 1809 - nvc_vt_build_cpuid_cache() Allocation Failure

### ISSUE THREAD

**Issue by InvisK** [Zero-Tang/NoirVisor#1]
Hello, i got Allocation Failure when im trying to start NoirVisor, for what i can trace is because nvc_vt_build_cpuid_cache return false by this block (vt_main.c line 491) : 

> 		cache->ext_leaf=noir_alloc_nonpg_memory((hvm->relative_hvm->ext_leaftotal+1)*sizeof(noir_vt_cpuid_info));
> 		if(cache->ext_leaf==null)
> 			*cache->ext_leaf=viext;
> 		else
>>>> 			return false;

how to fix it?, thank you so much.

**Comment by Zero-Tang** [comment]
Hi, thanks for the feedback. It seems that the overall project has overwhelming memory allocations. I'll try to optimize the allocation in future month. By now, my lab lacks free Intel machines. Thus any changes would remain untested.
If you wish to do on yourself, I would say the key point is to: allocate a big memory pool to put all the stuff inside.
Kind Regards.

**Comment by InvisK** [comment]
oh i think it's just a mistake, what you think about this change ?

> if(cache->ext_leaf==null)

to

> if(cache->ext_leaf)

we cant assign value to a null pointer

**Comment by Zero-Tang** [comment]
Well, I suppose this revision is correct. Thanks.
I didn't realize this mistake since this CPUID caching was not tested on Intel machine.
Close the issue if your test of the revision is successful. I will commit revision and push it as soon as possible.

**Comment by InvisK** [comment]
i think it's ok now but i got irql_not_less_or_equal BSOD at the startup, i will try to trace something before create new issue, thank you for the help.
