### ISSUE TITLE
cpuid

### ISSUE THREAD

**Issue by 9844201** [Zero-Tang/NoirVisor#15]
是否可以添加 虚拟 

cpuid std_leaf_index 

wmic CPU get ProcessorID
ProcessorId
BFEBFBFF000306C3

和
	{0x80000002, handle_ext_pname},
	{0x80000003, handle_ext_pname},

Processor Name: Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz

**Comment by Zero-Tang** [comment]
可以，你自己添加吧。
