### ISSUE TITLE
Win7 x64 测试蓝屏的原因

### ISSUE THREAD

**Issue by 9844201** [Zero-Tang/NoirVisor#19]
经过调试 发现 vcpu->ept_manager=(void*)nvc_ept_build_identity_map(); 获取到的值为NULL 所以跳到了alloc_failure
这个时候nvc_vt_cleanup里面的rhvm 为NULL ，然后执行了下面的代码if(rhvm->msr_bitmap.virt)
 所以蓝屏了

**Comment by Zero-Tang** [comment]
早在11.25的更新里就修好了，忘记关了。。。
