### ISSUE TITLE
AMD CPU 测试InlineHook的问题

### ISSUE THREAD

**Issue by 9844201** [Zero-Tang/NoirVisor#21]
AMD CPU 测试开了InlineHook 会导致什么东西死锁一样 （这是实体机）
![GIF 2021-10-31 13-53-46](https://user-images.githubusercontent.com/3508145/139570214-32f32dac-252a-4cbf-950c-712e4c49339e.gif)

**Comment by Zero-Tang** [comment]
更新随缘吧，Hook啥的我是真的不想再整了

**Comment by 9844201** [comment]
好吧
