### ISSUE TITLE
Clion

### ISSUE THREAD

**Issue by ddkwork** [Zero-Tang/NoirVisor#22]
请教下不安装vs2019的情况下，使用clion
ewdk最新版，clion始终无法构建项目的原因，
如果不安装vs的情况下可以通过ewdk生成exe dll
sys，那很给力啊，vs 60gb巨坑

**Comment by Zero-Tang** [comment]
我没玩过clion，不知道怎么配置。
总之就是配置编译器的选项，你照着项目里的编译脚本进行配置就行了。
我写C项目很少用IDE的，你可以理解为我通常会用Windows附件里的记事本写代码。
