### ISSUE TITLE
VM-Entry failed due to invalid control fields

### ISSUE THREAD

**Issue by tengan2020** [Zero-Tang/NoirVisor#24]
```C
[NoirVisor] Launching vCPU...
[NoirVisor] Error while launching the Guest! VMX Status: 1
[NoirVisor] Failed at VM-Entry, Code=7  Reason: VM-Entry failed due to invalid control fields!
[NoirVisor] -----------
[NoirVisor] Dumping VMCS Guest State Area...
[NoirVisor] Guest CS Segment - Selector: 0x10  Access-Rights: 0x209B  Limit: 0x0  Base: 0x0000000000000000
[NoirVisor] Guest DS Segment - Selector: 0x2B  Access-Rights: 0xC0F3  Limit: 0xFFFFFFFF  Base: 0x0000000000000000
[NoirVisor] Guest ES Segment - Selector: 0x2B  Access-Rights: 0xC0F3  Limit: 0xFFFFFFFF  Base: 0x0000000000000000
[NoirVisor] Guest FS Segment - Selector: 0x53  Access-Rights: 0x40F3  Limit: 0xBC00  Base: 0x0000000000000000
[NoirVisor] Guest GS Segment - Selector: 0x2B  Access-Rights: 0xC0F3  Limit: 0xFFFFFFFF  Base: 0xFFFF94001CC40000
[NoirVisor] Guest SS Segment - Selector: 0x18  Access-Rights: 0x4093  Limit: 0x0  Base: 0x0000000000000000
[NoirVisor] Guest Task Register - Selector: 0x40  Access-Rights: 0x8B  Limit: 0x67  Base: 0xFFFF94001CC50000
[NoirVisor] Guest LDT Register - Selector: 0x0  Access-Rights: 0x10000  Limit: 0x0  Base: 0x0000000000000000
[NoirVisor] Guest GDTR Limit: 0x57  Base: 0xFFFF94001CC51FB0  Guest IDTR Limit: 0xFFF  Base: 0xFFFF94001CC4F000
[NoirVisor] Guest Control & Debug Registers - CR0: 0x80050033  CR3: 0x00000004154F0000  CR4: 0xB52EF8  DR7: 0x400
[NoirVisor] Guest Special GPRs: Rsp: 0xFFFFFA0C7E047A10  Rip: 0xFFFFF803B8285330  RFlags:0x2  Ssp: 0x0000000000000000
[NoirVisor] Guest Activity State: 0  Interruptibility State: 0x0  Pending Debug Exceptions: 0x0
[NoirVisor] Guest EFER: 0xD01  PAT: 0x0  Debug Control: 0x0
[NoirVisor] Guest VMCS Link Pointer: 0xFFFFFFFFFFFFFFFF
[NoirVisor] Guest PDPTE0: 0x0  PDPTE1: 0x0  PDPTE2: 0x0  PDPTE3: 0x0
[NoirVisor] Pin-Based Controls: 0x16  Primary Controls: 0x96006172  Secondary Controls: 0x11010AA  Exception Bitmap: 0x0
[NoirVisor] VM-Exit Controls: 0x336FFB  VM-Entry Controls: 0x93FB
[NoirVisor] EPT Pointer: 0x6D9BC01E
[NoirVisor] Event Injection: 0x0
[NoirVisor] -----------
```
tested on Microsoft Windows [Version 10.0.22000.556] with Intel i5-8400 (VT-x & EPT are supported)

**Comment by Zero-Tang** [comment]
I failed to procure a replication of this bug. My test is performed on a physical machine with Windows 11 x64 installed, running on Intel Core i5-9400F, as shown in the screenshot attached below.
![Capture](https://user-images.githubusercontent.com/37060901/164238826-bb2a3ca5-7aa4-46fe-8114-e9278d318f05.PNG)

**Comment by tengan2020** [comment]
@Zero-Tang with manually set values
```C
Primary Controls: 0x9681F372  Secondary Controls: 0x19186E
VM-Exit Controls: 0x103EFFF  VM-Entry Controls: 0x213FF
```
works fine

**Comment by tengan2020** [comment]
@Zero-Tang also on another machine (Laptop) with Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz ( 2 cores ) just BSOD
```
DRIVER_IRQL_NOT_LESS_OR_EQUAL (d1)
An attempt was made to access a pageable (or completely invalid) address at an
interrupt request level (IRQL) that is too high.  This is usually
caused by drivers using improper addresses.
If kernel debugger is available get stack backtrace.
Arguments:
Arg1: ffff87808a973e20, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000000, value 0 = read operation, 1 = write operation
Arg4: fffff806820129a4, address which referenced memory
```
tested on Microsoft Windows [Version 10.0.18363.1082]
Minidump File: [042122-7312-01.zip](https://github.com/Zero-Tang/NoirVisor/files/8524267/042122-7312-01.zip)

**Comment by Zero-Tang** [comment]
Can you include a copy of the NoirVisor symbol? Even if it is compiled without any changes, my debugger cannot correctly identify symbol of the corresponding faulting `rip`.

**Comment by Zero-Tang** [comment]
> @Zero-Tang with manually set values
> 
> ```c
> Primary Controls: 0x9681F372  Secondary Controls: 0x19186E
> VM-Exit Controls: 0x103EFFF  VM-Entry Controls: 0x213FF
> ```
> 
> works fine

I guess these "manually set values" come from a known working hypervisor.
Regardless, I looked up the manual. Try to remove line 527 in vt_main.c, where NoirVisor enforces the processor to use GPA for Intel PT, and let me know the result.

**Comment by tengan2020** [comment]
@Zero-Tang
> I guess these "manually set values" come from a known working hypervisor. 

Yes, you are right

> Regardless, I looked up the manual. Try to remove line 527 in vt_main.c, where NoirVisor enforces the processor to use GPA for Intel PT, and let me know the result.

it works great now, thanks!

>Can you include a copy of the NoirVisor symbol? Even if it is compiled without any changes, my debugger cannot correctly identify symbol of the corresponding faulting rip.

I'm sorry, I completely forgot about that.
New Minidump + PDB's: [minidump.zip](https://github.com/Zero-Tang/NoirVisor/files/8528105/minidump.zip)

**Comment by Zero-Tang** [comment]
I think the index is incorrect as well as you do. Try to replace `index` with `i` in this `for` block. \
This function is used for MTRR emulation. If there is something wrong with emulation, system might went into BSOD with code 0x124. So please keep NoirVisor running for several minutes. If MTRR is not properly emulated, the BSoD will usually trigger in a quarter.

**Comment by tengan2020** [comment]
after apply changes
```C
while(cur)
{
	if(hpa>=cur->gpa_start && hpa<cur->gpa_start+page_2mb_size)
	{
		for(u32 i=0;i<512;i++)
		{
			if(regardless || cur->virt[i].ignored1 || memory_type<cur->virt[i].memory_type)
				cur->virt[i].memory_type=memory_type;
			cur->virt[i].ignored1=true;			// Use the ignored bit to indicate that this page is marked by MTRR.
		}
	}
	cur=cur->next;
}
```
got something like this: the system began to freeze very much, but not crashed

https://user-images.githubusercontent.com/104060380/164405400-635e8698-1c3b-483d-ab51-549426407672.mp4

**Comment by Zero-Tang** [comment]
It looks like i5-x200U shares this bug. I replicated this issue on i5-5200U.
I am investigating.

**Comment by tengan2020** [comment]
@Zero-Tang can I ask you, maybe you also can help me. In which direction should I study the problem?
When EPT hooked page get executed it cause IRQL_NOT_LESS_OR_EQUAL BSOD.
```C
Arguments:
Arg1: 0000000000000000, memory referenced
Arg2: 0000000000000002, IRQL
Arg3: 0000000000000001, bitfield :
	bit 0 : value 0 = read operation, 1 = write operation
	bit 3 : value 0 = not an execute operation, 1 = execute operation (only on chips which support this level of status)
Arg4: fffff8035133c330, address which referenced memory
```
```C
OriginalPage = 0x14033C000
Execution Instruction = 0x14033C330 <- BSOD
NtSetInformationFile = 0x14033C560
```

**Comment by tengan2020** [comment]
@Zero-Tang can you give me some advice, nvc_vt_wrmsr_handler/nvc_vt_rdmsr_handler is not handle all write/read MSR execution. For exmaple:
 ```C
__readmsr(0x123) // just random MSR index
```

**Comment by Zero-Tang** [comment]
NoirVisor uses MSR-bitmap to select only accesses of a few MSRs to be intercepted.
If you wish to intercept all MSRs, remove the line `proc_ctrl.use_msr_bitmap=1` in function `nvc_vt_setup_procbased_controls`. If you do so, make sure your MSR-handler is well-prepared.
MSRs out of the range of `0x0-0x1FFF` and `0xC0000000-0xC0001FFF` are always intercepted regardless of whether MSR-bitmap is active or not.

**Comment by Zero-Tang** [comment]
The original issue in this thread is already solved ten days ago, so I am closing this issue.
The new issue about the system went freezing is now transferred in issue #25. Discussion regarding this issue should go to that thread.
If you have something else to discuss about, feel free to [join the discord](https://discord.gg/5cKn5FdK6U) server.
