### ISSUE TITLE
System freezes on some Intel laptops

### ISSUE THREAD

**Issue by Zero-Tang** [Zero-Tang/NoirVisor#25]
As noted in follow-ups in issue #24, it is confirmed that system might freeze on some Intel laptops. The i5-6200U and i5-5200U are confirmed to have this issue. The i7-7500U, nevertheless, does not have this issue.
As a part of investigation, the system does not seem to freeze if EPT is disabled.
I suspect there is a bug in MTRR emulation.

**Comment by tengan2020** [comment]
@Zero-Tang After a lot of researching and testing, I found out that in `vt_ept.c!nvc_ept_update_pde_memory_type` we must regardless update memory type if it is caused by changing the MTRR structure ( or first initialization of EPT ).

also we should correct ignore bit ( as marker for MTRR page ) in `vt_ept.c!nvc_ept_update_pde_memory_type`
```C
                                       there ||
                                             \/
if (regardless || eptm->pde.virt[index].ignored0 || memory_type < eptm->pde.virt[index].memory_type)
	eptm->pde.virt[index].memory_type = memory_type;
eptm->pde.virt[index].ignored0 = true;				// Use the ignored bit to indicate that this page is marked
```
and in `vt_ept.c!nvc_ept_update_per_var_mtrr`:
```C                                                                                                                                                               
                                                                                            there ||
                                                                                                  \/
if (mask_target == mask_base)nvc_ept_update_pde_memory_type(eptm, mask_addr, (u8)phys_base.type, true);
```

**Comment by Zero-Tang** [comment]
That's a great job!

**Comment by Zero-Tang** [comment]
Someone else reported that this issue still persists: system still went freezing even if the fix is applied. His laptop is Asus TUF FX80G with Intel Core i7-8750H.
I'll purchase one and investigate when I have the budget.
