### ISSUE TITLE
Expected Intercept Code: 0x400

### ISSUE THREAD

**Issue by progromyang** [Zero-Tang/NoirVisor#26]
Hello, my elder. Please consult you

Expected Intercept Code: 0x400

Using NVC_ svm_ nested_ pf_ Handler to switch the pages of inline hook,

However, page switching is not found in the function, but primary CR3 and secondary CR3 are used

Do you use switching CR3 to hide the page in the design of this function?

**Comment by Zero-Tang** [comment]
First of all, I would like to remind you that feel free to speak Chinese if you have difficulty in speaking English. Your expression in English is somewhat incoherent. Nevertheless, if you prefer communicating in English, then so be it.

The short answer is: yes, NoirVisor switches NCR3.
The long explication is: read these notes.
https://github.com/Zero-Tang/NoirVisor/blob/master/doc/stealthy_hooks.md#hide-inline-hooks-via-amd-vnpt
https://github.com/Zero-Tang/NoirVisor/tree/master/src/svm_core#stealth-inline-hook-algorithm

Feel free to come back if you have further questions.

**Comment by progromyang** [comment]
真的非常感谢前辈对我的解答与指点，我先好好阅读一下您的笔记，非常感谢，谢谢
