### ISSUE TITLE
抱歉前辈，再次打扰到您了。

### ISSUE THREAD

**Issue by progromyang** [Zero-Tang/NoirVisor#31]
您好前辈，我尝试编译您开源的 https://github.com/Zero-Tang/NoirVisor 项目。
disasm\build 在目录中 我尝试通过EWDK 17.1.5 来运行编译 compchk_win11x64/compfre_win11x64。
但是错误提示：
disasm.c
ZYDIS_STATIC_DEFINE was renamed to ZYDIS_STATIC_BUILD.
..\disasm.c(24): error C2065: 'ZYDIS_ADDRESS_WIDTH_64': undeclared identifier
..\disasm.c(25): error C2065: 'ZYDIS_ADDRESS_WIDTH_32': undeclared identifier
..\disasm.c(26): error C2065: 'ZYDIS_ADDRESS_WIDTH_16': undeclared identifier
..\disasm.c(34): warning C4013: 'ZydisDecoderDecodeBuffer' undefined; assuming extern returning int
..\disasm.c(35): warning C4133: 'function': incompatible types - from 'char *' to 'const ZydisDecodedOperand *'
..\disasm.c(35): warning C4244: 'function': conversion from 'ZyanUSize' to 'ZyanU8', possible loss of data
..............................
我尝试在源代码中寻找 ZYDIS_ADDRESS_WIDTH_64，ZYDIS_ADDRESS_WIDTH_32，ZYDIS_ADDRESS_WIDTH_16，并没有找到，
Zydis项目中虽然有ZydisDecoderDecodeBuffer函数的定义，但是提示确说没有定义此函数。。
打扰到前辈非常抱歉，希望您可以在百忙之中可以看到我的来信 谢谢

**Comment by Zero-Tang** [comment]
应该是因为你没通过git来下载代码，所以出了版本依赖错误。请用git下载使用git管理的代码。
```
git clone --recurse-submodules https://github.com/Zero-Tang/NoirVisor
```
NoirVisor现在引用的zydis版本还是v3.2.1，没有升级到v4。

**Comment by progromyang** [comment]
亲爱的前辈，按照您的方法已经顺利编译成功了，真是这个静态库版本问题。
真的非常感谢您每一次的耐心解答，我一时间不知道应该怎样表达对您的感激。
想向您邮寄一份我们陕西的特产，希望您可以留一下您的联系方式。

**Comment by Zero-Tang** [comment]
不必了，你的谢意我心领了。食品之类的特产通过邮寄的方式大概率无法通过美国海关，国际运输也不便宜。
