### ISSUE TITLE
Why judge so many "write back"?

### ISSUE THREAD

**Issue by Oxygen1a1** [Zero-Tang/NoirVisor#36]
老哥，看你代码判断是否支持intel vtx的时候，判断了vmcs wb内存
ept支持的时候，也判断了如下
    /**
     * [Bit 14] When set to 1, the logical processor allows software to configure the EPT paging-structure memory type to be
     * write-back (WB).
     */
    uint64_t memory_type_write_back                                  : 1;

请问为什么要判断是不是写回呢，这个很重要吗？

**Comment by Zero-Tang** [comment]
你贴的不是NoirVisor的代码吧。。。
因为一般情况下我们到的申请的内存默认就是WB。

**Comment by Oxygen1a1** [comment]
![image](https://github.com/user-attachments/assets/eff8bdf3-490a-4307-b8c2-166ac07fc898)
这个地方，

**Comment by Oxygen1a1** [comment]
懂了老哥，是我们申请的内存是WB,所以要判断这些EPT页表配置是否支持WB类型内存对吗?

**Comment by Zero-Tang** [comment]
> ![image](https://private-user-images.githubusercontent.com/98365671/383985784-eff8bdf3-490a-4307-b8c2-166ac07fc898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODc4MzAsIm5iZiI6MTczMDk4NzUzMCwicGF0aCI6Ii85ODM2NTY3MS8zODM5ODU3ODQtZWZmOGJkZjMtNDkwYS00MzA3LWI4YzItMTY2YWMwN2ZjODk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDEzNTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZTQzNTBhNWJiMDM1NzI5MGI3OTg3NzE1YTRiYzc3M2FiZmE2MWZiMTVjYmQ2NmEwNmE4YzZkYThiY2Y5MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hn5ZOPE2YR3fJYBJ3DhoCnSI3jufYQIUJ1cprjRxDVY) 这个地方，

你这贴的截图也不是判断WB的。。。



> 懂了老哥，是我们申请的内存是WB,所以要判断这些EPT页表配置是否支持WB类型内存对吗?

对的，需要判断是否支持WB。

**Comment by Oxygen1a1** [comment]
不好意思，贴错了，了解了，感谢老哥回复
