### ISSUE TITLE
Is there a plan to support a simpler hook api?

### ISSUE THREAD

**Issue by stonedreamforest** [Zero-Tang/NoirVisor#6]
hello,
It seems that the user needs to manually construct the code,Any automation api similar to [Microsoft detours](https://github.com/microsoft/Detours): DetourAttach
https://github.com/Zero-Tang/NoirVisor/blob/9f283568e9c9b4662f3d6958f2d9f7838398e0ec/src/xpf_core/windows/hooks.c#L136

**Comment by Zero-Tang** [comment]
Hi,
thanks for the suggestion. By now, there are only AMD machines in my possession, so I have to develop NPT-based inline hook demo before I work on this issue so that I may test code.
I'll put this issue on the plan.

**Comment by Zero-Tang** [comment]
In the previous commit, I added API to address this issue, though NPT-based stealth inline hook is incomplete. Now, hooking API should become easier.
Close the issue if you find this has satisfied your demand. I will close this issue after 15 days if no response.
