### ISSUE TITLE
Use a build system or VS projects instead of batch scripts

### ISSUE THREAD

**Issue by bugproof** [Zero-Tang/NoirVisor#7]
First of all, I'm amazed by your project. It's probably the only hypervisor that currently supports both intel and amd and a great learning resource for a person like me trying to learn more about hypervisors.

Why do you use .bat scripts to build the windows driver? Don't you use visual studio to develop? Other than that it would maybe be better to use some build system like CMake or premake. And it should be possible to build using WDK downloaded with Vistual Studio Installer. What do you think about it?

**Comment by Zero-Tang** [comment]
The reason that I use batch scripts to build windows driver is my personal preference. Using batch to invoke compiler and linker gives me the best intuitive and precise building experience.
Though there is Visual Studio installed in my computer, I rarely use it to develop C projects. Instead, I use Visual Studio to develop Visual Basic .NET projects (e.g. [NoirVisorLoader](https://github.com/Zero-Tang/NoirVisorLoader) is a VB.NET project).

**Comment by bugproof** [comment]
What do you use to develop C projects?

If you want I could setup some build system using cmake or premake that would generate projects and find WDK on your system automatically, or just add VS projects. Or I could do it in my repo and add NoirVisor as a git submodule.

**Comment by Zero-Tang** [comment]
I use any working text editor to develop C projects - that is, Notepad in Windows Accessories is good enough to do development. The build system for this project will keep as is as I plan to port NoirVisor to other platforms like Linux (I may use bash) etc.

**Comment by bugproof** [comment]
@Zero-Tang I will treat that as a joke 😄 notepad in windows accessories doesn't have any syntax coloring nor anything.
