### ISSUE TITLE
noir_vt_invept和noir_vt_invvpid的问题

### ISSUE THREAD

**Issue by huoji120** [Zero-Tang/NoirVisor#8]
在vt_hv.asm中,
第66行一个是 	invept rcx,xmmword ptr [rdx]，而不是	invept xmmword ptr [rdx],rcx
看起来是作者故意的?

**Comment by Zero-Tang** [comment]
这确实是我故意的，因为`MASM`汇编器定义的`invept`和`invvpid`指令的操作数顺序与`Intel VMX`手册中所定义的相反，按正常顺序则无法编译。指令名后跟的先是内存操作数，然后才是寄存器操作数，也就是`invept xmmword ptr[rdx],rcx`。编译后用反汇编器查看，是正常的。
![ida_invept](https://user-images.githubusercontent.com/37060901/82077723-e729b400-96ad-11ea-985e-7c66b00bbfea.PNG)
